language: rust
sudo: false
rust:
  - nightly

matrix:
    include:
        - os: linux
          env: FEATURES="unstable"; FEATURES="unstable force-inprocess"; FEATURES="unstable force-posix-shm"
        - os: osx
          env: FEATURES="unstable"; FEATURES="unstable force-inprocess"

notifications:
  webhooks: http://build.servo.org:54856/travis

script:
  - cargo build --features "$FEATURES"
  - cargo test --features "$FEATURES"
